#
# /etc/pacman.conf
#
# Custom Arch Installer Configuration
#

[options]

HoldPkg     = pacman glibc
Architecture = auto

Color
ILoveCandy
CheckSpace
VerbosePkgLists
ParallelDownloads = 10
DownloadUser = alpm

SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

#
# Repositories
#

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

#
# Optional repositories
#

#[core-testing]
#Include = /etc/pacman.d/mirrorlist

#[extra-testing]
#Include = /etc/pacman.d/mirrorlist

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist

#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs